[package]
name = "charm_game"
version = "0.0.1"
authors = ["SpiveeWorks <spiveehere@gmail.com>"]

[dependencies]
piston_window = "0.72.0"
charm_internal = { path = 'lib-internal' }
ref_links = { path = 'lib-links' }

